import { Inter, Audiowide, Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "./Sections/Navbar";
import Footer from "./Sections/Footer";
import Wrapper from "../wrapper";
import AuthProvider from "./Provider";

const inter = Inter({ subsets: ["latin"] });
const audiowide = Audiowide({ subsets: ["latin"], weight: "400" });
const outfit = Outfit({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Shoes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${audiowide.className} ${outfit.className}`}>
        <AuthProvider>
          <Wrapper>
            <Navbar />
            {children}
            <Footer />
          </Wrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
