import { Inter, Audiowide,Outfit } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
const audiowide = Audiowide({ subsets: ["latin"],weight: "400"  });
const outfit = Outfit({ subsets: ["latin"],weight: "400"  });
import Navbar from "./Sections/Navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${audiowide.className} ${outfit.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
